version: '3'

services:
    node:
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
          - "7000-7100:7000"
        networks:
            - testing_net

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
