version: '3'

services:
    node:
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
          - "7000-7100:7000"
        depends_on:
          - jaeger
        environment:
            - JAEGER_AGENT_HOST=jaeger
            - JAEGER_AGENT_PORT=6831
        links:
          - jaeger
        networks:
            - testing_net

    jaeger:
        image: jaegertracing/all-in-one:latest
        environment:
          - COLLECTOR_ZIPKIN_HTTP_PORT=9411
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "14268:14268"
            - "9411:9411"
        networks:
          - testing_net
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
