version: '3'

services:
    node:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - testing_net

    propagator:
        build:
            context: .
            dockerfile: Dockerfile-propagator
        networks:
            - testing_net

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16